apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-client
  template:
    metadata:
      labels:
        app: stock-client
    spec:
      containers:
      - name: client2
        image: molka0204/stock-client:v2
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: app-configmap
