version: '3'
services:
  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb2
    networks:
      - stock-network

  # Service serveur Node.js
  server:
    build:
      context: ./backend
    container_name: server2
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/client
    depends_on:
      - mongodb
    networks:
      - stock-network

  # Service client React
  client:
    build:
      context: ./client
    container_name: client2
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - stock-network

# Réseau
networks:
  stock-network:
    driver: bridge
