apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: stock-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 
      nodePort: 30003
  type: NodePort
